### ISSUE TITLE
Highlight new tab

### ISSUE THREAD

**Issue by vboerchers** [nralbrecht/pinned-tab-fix#1]
It would be great if the new tab would be highlighted somehow if it is opened as a background tab since
- the tab is opened pretty far from the link your are focused on when clicking it and
- a background tab is not highlighted.

**Comment by nralbrecht** [comment]
Could you please elaborate on that a bit more. Would you want somthing like a color flashing of the tab or a text based highlight? 

My personal view on this is, that something so specific would be better off in a separate add-on.

**Comment by vboerchers** [comment]
Well, I thought of some sort of flashing perhaps as if it would be the active tab for a second or so.

**Comment by rnc** [comment]
Maybe something like https://userstyles.org/styles/94667/selected-tab-blue-font-color-for-ft-deepdark ?

**Comment by nralbrecht** [comment]
I had a nother look at your suggestion but came to the conclusion, that with the current state of the add-on API it is not possible to implement this.

- Google Chome has [tab highlighting](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/highlight). This is not available in Firefox.
- Using CSS to alter the appearance of Firefox itself from an add-on is not allowed.
- [Themes](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/theme) are only able to change the header image and set text and accent colors.

I also could not find any sign that this is going to change any time soon.

**Comment by vboerchers** [comment]
Thanks for letting me know. I'm still a happy user despite of missing highlighting :-)
