### ISSUE TITLE
Tab containers support

### ISSUE THREAD

**Issue by Exagone313** [nralbrecht/pinned-tab-fix#10]
Hi,

When an opened link from a pinned tab would be opened in a [container](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/), it opens on the left, after the first non-pinned tab. In fact I see the tab bar moving to the right then to the left.

**Comment by Exagone313** [comment]
It appears that only links opened in another container that the current one are concerned.

**Comment by nralbrecht** [comment]
I did not get notified about your issue for some reason. 🤔 I am looking into it. Expect something in the coming days.

**Comment by Exagone313** [comment]
I have worked on two solutions:
* one over complicated that saves the last created tab: 41bcc2021c706409663d56c9e2ca1bfb6e268f17 (not clean enough)
* one that doesn't save the new tab if it is loading: f4759a8b63381ceb447d63dc20b15e2a3aa6815f + 32056e397376ff12ef3313944d611e7d1845ec55 (it also magically fixes the issue #18 without my suggested change, but it possibly is a race condition)

I'll submit a PR once I'm confident in the work done.

**Comment by Exagone313** [comment]
@nralbrecht, do you plan to continue maintaining this addon? I tried to publish a new addon with the bugs fixed, however Mozilla is not accepting forks without significant changes:
> If the add-on is a fork of another add-on, the name must clearly distinguish it from the original and provide a significant difference in functionality and/or code.

**Comment by nralbrecht** [comment]
I do plan on maintaining the plugin. I am sorry for the lack of communication from my side. I did try to get it to work my self with little success. Your work is very much appreciated and i would obviously publish a new version with your changes. Could you create a pull request with your changes? I would try it out and publish it.

**Comment by Exagone313** [comment]
I will do that, I refrained to do so as I had questions about retrocompatibility (as described above).

**Comment by nralbrecht** [comment]
I tested the changes and as far as I can see they look to solve the issue.

**Comment by Exagone313** [comment]
Thank you, sorry for not being as active as I should have been on this issue.
