### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by AussieGit** [nralbrecht/pinned-tab-fix#12]
Has stopped working. Any links clicked from my 2 pinned tabs are opened immediately after the pinned tabs and not at the end. Using v2.1.0 on Firefox 57.0.2 64x on Windows 7

**Comment by nralbrecht** [comment]
Its working for me using Firefox 57.0.2 on Windows 10. 
How are you opening new tabs? (e.g. strg-left click)
Do you have any other addons that change behavior of tabs?

**Comment by AussieGit** [comment]
I use 3 Tab extensions other than yours in Tree Style Tabs, OneTab & Tab Suspender but even with all 3 disabled or a mix of the 3, Pinned Tab Fix doesn't work.
 I only have 2 pinned tabs in Netvibes RSS reader and Twitter which of course, have hundred of links I click. I click on the links with middle button mouse click but even using Ctrl-Left click or Right Click- "Open Link in Tab" still same result.
BTW, thanks for such prompt reply. Great support service.

**Comment by nralbrecht** [comment]
I tried to replicate your problem but on every platform I tried, it worked as expected. I don't really know I can help you.
- Have you changed anything in about:config?
- Have you tried the new update? (Firefox 57.0.3)
