### ISSUE TITLE
Stopped working on FF 60.0b3

### ISSUE THREAD

**Issue by RalfJung** [nralbrecht/pinned-tab-fix#13]
I updated my Firefox to version 60.0b3 yesterday and just realized that this plugin is now broken: When I click a link in a pinned tab, the new tab opens all the way to the left, which is not where I want it.

**Comment by RalfJung** [comment]
Same with 60.0b5

**Comment by nralbrecht** [comment]
Thanks for letting me know. I will have a look into it.

**Comment by RalfJung** [comment]
I reported this upstream at https://bugzilla.mozilla.org/show_bug.cgi?id=1450710 to make the Firefox team aware that they changed some extension behavior.

**Comment by nschneid** [comment]
I just upgraded Firefox to 60.0, and it's broken.

**Comment by nralbrecht** [comment]
Alright it should now work with FF 60. The visual scrolling and flashing got quite a bit worse but I could not come up with a workaround. 🙄
