### ISSUE TITLE
Recently closed tab is moved to the right if restored from a pinned tab

### ISSUE THREAD

**Issue by Forkest** [nralbrecht/pinned-tab-fix#14]
A tab can be restored either via Undo Close Tab or History, Recently Closed Tabs.

**Comment by nralbrecht** [comment]
Oh you are right. I will see what I can do.

**Comment by Forkest** [comment]
Sadly, 0211a51 doesn't fix it for me. Firefox 52 ESR here. lastClosed is undefined.

And you've mixed up the negations there. I believe you've meant what's proposed in #16.

**Comment by nralbrecht** [comment]
Interesting, because it worked perfectly for me in Firefox 62. Thanks a lot.

**Comment by nralbrecht** [comment]
Hence this isn't working in Firefox 52 ESR I guess I have another go at it 😀

**Comment by nralbrecht** [comment]
Allright now it should work. 👍

**Comment by Forkest** [comment]
Well, now it stopped working for tabs normally opened from pinned tabs... 😕
So the add-on became essentially non-functional.

lastClosed is always true.

**Comment by nralbrecht** [comment]
Yes but only when I load the add-on via addons.mozilla.org. When debugging it in v52 ESR it works with out any problems. 🤦‍♂️

For the moment I deactivated the new version in the store. So it should downgrade automaticly again 😒 

I guess I give it another try, but I am kinda out of ideas...

**Comment by nralbrecht** [comment]
Ok, I rewrote the core logic and had some mixed results with Firefox 52 ERS.

Does it work for you?
If not:
- try restarting your browser after installing
- try downloading the xpi from addons.mozilla.org
    - go to the [addon page](https://addons.mozilla.org/de/firefox/addon/pinned-tabs-fix/)
    - right click on "add to firefox" and select "save link as..."
    - save somewhere
    - go to the [add-on page](about:addons)
    - select "install add-on from file"
    - install the downloaded file

**Comment by Forkest** [comment]
The add-on has autoupdated already, and yes, it works well!

I have to say that I'm impressed with your solution, because I've thought only about detecting the true parent tab, and that seems to be a pretty complex task with a much more hacky solution, from what I've found from the Tree Style Tab source code.
Of course, the downside is that it falsely sends to the end a tab restored at the place directly after pinned tabs, but that shouldn't be much of an issue, given the audience of this add-on (people who have a lot of tabs, I suppose).
Also it could make sense to test whether it'll continue to work with some pinned tabs [hidden](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/hide) (I'm not sure if that affects their index).

Thank you for the fix and not giving up 🙂

**Comment by nralbrecht** [comment]
Thank you 🙂 
I don't think that hidden tabs are a problem, hence that is only a property of a tab but I'l have a look into it. 

Cheers!
