### ISSUE TITLE
Doesn't work on Firefox 82.0

### ISSUE THREAD

**Issue by kevinptt0323** [nralbrecht/pinned-tab-fix#17]
As title, this plugin seems not working on latest version.
* Firefox Version: 82.0
* OS: Linux 5.7.17 Debian

**Comment by nralbrecht** [comment]
Thanks for reporting. I will have a look in to it.

**Comment by kevinptt0323** [comment]
Doesn't work on Firefox 81.0.2 and 82 on Windows 10 either.

**Comment by nralbrecht** [comment]
I was not able to reproduce the problem. I have tried to use it on the following Systems with out a flaw:
- Firefox 80 and 82.0 on Arch Linux
- Firefox 82.0 on Windows 10

Could you describe how you tried to use it, including your expected behavior.

**Comment by Buratinator** [comment]
Stopped working for me too after FF updated to 82.0 on Windows 10, x64).

**Comment by kevinptt0323** [comment]
It seems like a similar feature for the latest Tree Styles Tab which also changes the default behavior. It works again after setting TST properly.
Thanks for your support!

**Comment by nralbrecht** [comment]
Good to hear! @Buratinator if it still does not work for you, feel free to open another Issue.

**Comment by Buratinator** [comment]
I confirm that it's indeed a conflict with TST, didn't know they had this. Thanks!
