### ISSUE TITLE
Add-on should recognize "open tabs in the foreground" setting

### ISSUE THREAD

**Issue by vboerchers** [nralbrecht/pinned-tab-fix#2]
Tabs are always opened in the background, even if I have switched on General -> "When I open a link in a new tab, switch to it immediately", see https://support.mozilla.org/en-US/kb/startup-home-page-tabs-download-settings

**Comment by nralbrecht** [comment]
At the moment you can turn on the wanted behavior in the add-on specific preferences. 
I am going to change this, so that the mentioned option is used instead.
