### ISSUE TITLE
Causes page load slowness in Firefox 102?

### ISSUE THREAD

**Issue by nschneid** [nralbrecht/pinned-tab-fix#21]
I recently started experiencing slow/unreliable page loads for some sites (including GitHub), and after disabling and reenabling various extensions to isolate the problem, Pinned Tab Fix may be the culprit. Is it possible that a recent API change has broken something?

**Comment by nralbrecht** [comment]
I would be surprised by that, as this Add-On is pretty slim. I was not able to notice any problems on my installation. I also was not able to find any API changes in the change log that should impact the Add-On.

Can you share your operating system and if you are using the "Open tabs in foreground" option?

**Comment by nschneid** [comment]
Thanks for looking into this.

macOS 12.4

Open tabs in foreground: off.

**Comment by nschneid** [comment]
OK I am experiencing the problem again with the extension disabled, so probably a false alarm. Thanks for bearing with me!
