### ISSUE TITLE
2.0.4 Installation problems

### ISSUE THREAD

**Issue by rnc** [nralbrecht/pinned-tab-fix#3]
Installing add-on from mozilla.org I get

```
*************************
A coding exception was thrown in a Promise rejection callback.
See https://developer.mozilla.org/Mozilla/JavaScript_code_modules/Promise.jsm/Promise

Full message: TypeError:  is not iterable
Full stack: AddonInstall.prototype.initLocalInstall/<@resource://gre/modules/addons/XPIProvider.jsm:5349:1
Handler.prototype.process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:940:21
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:816:7
this.PromiseWalker.scheduleWalkerLoop/<@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:750:11
openTabPrompt@resource://gre/components/nsPrompter.js:417:13
ModalPrompter.prototype.openPrompt@resource://gre/components/nsPrompter.js:532:17
ModalPrompter.prototype.alert@resource://gre/components/nsPrompter.js:602:9
```

**Comment by nralbrecht** [comment]
Which version of Firefox and operating system are you using?
Does this bug apply to your situation: https://bugs.launchpad.net/ubuntu/+source/firefox/+bug/1628014
If that is the case please consider upgrading to the newest Firefox version.

**Comment by rnc** [comment]
Apologies, using 49.0.2 on Fedora 24.

**Comment by rnc** [comment]
If people on that Ubuntu bug report state that Firefox 50 solves it, given 50 is in testing repositories [1] for Fedora 23,24 and 25 it may be worth waiting until it is released and retest then?
[1] : https://bodhi.fedoraproject.org/updates/?packages=firefox

**Comment by nralbrecht** [comment]
As it is now pushed to stable, yes please retest.

**Comment by rnc** [comment]
Will do as soon as it hits the update repos :-)

**Comment by rnc** [comment]
I can confirm that the problems goes away with version 50 on Fedora 24.
