### ISSUE TITLE
Pinned tab opening new tabs on left not right

### ISSUE THREAD

**Issue by rnc** [nralbrecht/pinned-tab-fix#5]
I am seeing new tabs opened from a pinned tab open on the leftmost instead of the right after all the other tabs. I am using Firefox 50 on Fedora 24.

**Comment by nralbrecht** [comment]
I can't find any problems. It works as promised using Firefox 50 on Windows 10. The used API's shuld also be supported.
Maybe you have a look in to the Add-on Console:
`about:debugging > activate debugging > debug Pined Tab Fix > Console tab`

**Comment by rnc** [comment]
I couldn't see anything obvious in the logging. One thing I have noticed - for a link that is to another site:

If I do 'right-click / Open link in new tab' it works fine.
If I do 'left click' , according to https://support.mozilla.org/en-US/kb/pinned-tabs-keep-favorite-websites-open#w_how-are-pinned-tabs-different-than-normal-tabs it should open a new tab. This it does, but its _this_ tab that is opened on the left, not on the right.

**Comment by rnc** [comment]
I've run both versions through the debugger and the results are
1. Either with the 'right click/open link in new tab' or 'ctrl-click' the lastActiveTab object is filled in and correctly set to pinned=true.
2. With the 'left click' but to an external site, the lastActiveTab = false.

I do see that the onActivated function should set the lastActiveTabId correctly. However , it does not always seem to be called consistently.

**Comment by nralbrecht** [comment]
All right, I haven't had those links in my pined tabs but this should fix the problem. The update will go through validation in a few hours.

**Comment by pbenedict** [comment]
I am using Firefox 65. I have not been able to get any pins appearing on the right. Is this add-on still being supported?

**Comment by nralbrecht** [comment]
Yes I still support this Plugin. On my Machine it works like it should.
You mentioned moving "pins". This add-on is supposed to move new tabs opened from a pinned tab on the right. If you actually ment new tabs please just open a new issue.
