### ISSUE TITLE
Links opened in non-pinned tabs open at the end too

### ISSUE THREAD

**Issue by Forkest** [nralbrecht/pinned-tab-fix#6]
The add-on should affect only pinned tabs, but it broke the normal behavior in other tabs for me. For example, clicking on a Google result in a non-last non-pinned tab opens a new tab at the end. Related preference: `browser.tabs.insertRelatedAfterCurrent` (I have it set to `true`, looks like it's a default value).

**Comment by nralbrecht** [comment]
Alright, this will do the trick. The update should be validated in the next few hours. Looks like I didn't test well enough. =)

ps: Even though I would like to make this dependent on the browser preference, there is and never will be a API for me to access them...

**Comment by Forkest** [comment]
Sorry for the late response, had to wait for the review to install and test it. It works well now, thank you for the fast fix and for the extension itself.

As for the preference access, there is [a request for it](https://webextensions.uservoice.com/forums/315663-webextension-api-ideas/suggestions/9437394-add-an-api-to-monitor-and-alter-existing-about-con), although it's indeed doubtful that it'll be implemented.
