### ISSUE TITLE
Prevent tab bar from scrolling to the left

### ISSUE THREAD

**Issue by tuetschek** [nralbrecht/pinned-tab-fix#7]
Hi,

thanks for this add-on, it's great! There's just one thing – if I have many tabs open and the tab bar is scrolled on the far right and I open a new tab from a pinned site, the new tab is correctly opened on the right of the tab bar, but the tab bar now scrolls left, so I can't see the newly opened tab. Could this be fixed somehow?

Thanks,
Ondrej

**Comment by nralbrecht** [comment]
Thank you very much.

I noticed the same problem. It probably has something to do with a change in the recent Firefox update v52. Unfortunately I can't find anything in the change logs that would apply. I am going to try to find the change in the debugger.

Nils

**Comment by nralbrecht** [comment]
Alright the update should go live as soon as it is approved.

**Comment by tuetschek** [comment]
That's great – thank you!
