### ISSUE TITLE
Links opened from other applications don't always get focues

### ISSUE THREAD

**Issue by RalfJung** [nralbrecht/pinned-tab-fix#8]
## Steps to reproduce

1. Have a pinned tab, and focus it.
2. Click a link in another application while Firefox is the default browser

## Expected behavior

The link should be opened and focused in a new tab. This happens without the add-on.

## Actual behavior

The link is opened in a new tab, but then the focus is moved back to the pinned tab.

**Comment by nralbrecht** [comment]
I finally found some time to fix the bugs. I submitted the new version and it will probably be validated and online in a couple of hours.
